# Generated by Django 6.0 on 2025-12-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='passcode',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
