# Generated by Django 6.0.1 on 2026-01-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochats', '0003_room_current_actor_room_current_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('host_only', 'Host Only')], default='normal', max_length=10),
        ),
    ]
