# Generated by Django 6.0 on 2026-01-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochats', '0004_room_game_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='game_mode',
        ),
        migrations.AddField(
            model_name='room',
            name='current_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
